apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "taskd.fullname" . }}
  labels:
    {{- include "taskd.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "taskd.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "taskd.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "taskd.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      shareProcessNamespace: true
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: CERT_CN
              value: {{ .Values.env.CERT_CN | quote }}
            - name: CERT_ORGANIZATION
              value: {{ .Values.env.CERT_ORGANIZATION | quote }}
            - name: CERT_COUNTRY
              value: {{ .Values.env.CERT_COUNTRY | quote }}
            - name: CERT_STATE
              value: {{ .Values.env.CERT_STATE | quote }}
            - name: CERT_LOCALITY
              value: {{ .Values.env.CERT_LOCALITY | quote }}
            - name: TASKD_ADMIN_ENABLED
              {{- if .Values.env.TASKD_ADMIN_ENABLED }}
              value: "1"
              {{- else }}
              value: "0"
              {{- end }}
            {{- if .Values.env.TASKD_ADMIN_USER }}
            - name: TASKD_ADMIN_USER
              value: {{ .Values.env.TASKD_ADMIN_USER | quote }}
            {{- end }}
            {{- if .Values.env.TASKD_ADMIN_PASS }}
            - name: TASKD_ADMIN_PASS
              value: {{ .Values.env.TASKD_ADMIN_PASS | quote }}
            {{- end }}
            {{- with .Values.env.extra }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            {{- if .Values.env.TASKD_ADMIN_ENABLED }}
            - name: admin
              containerPort: 8080
              protocol: TCP
            {{- end }}
            - name: taskd
              containerPort: 53589
              protocol: TCP
          volumeMounts:
            - mountPath: /var/taskd
              name: data
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: data
          {{- if and .Values.persistence.enabled .Values.persistence.existingClaim }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim }}
          {{- else if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "taskd.fullname" . }}
          {{- else }}
          emptyDir: {}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
