apiVersion: v1
kind: Service
metadata:
  name: {{ include "taskd.fullname" . }}
  labels:
    {{- include "taskd.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.taskd.port }}
      targetPort: 53589
      protocol: TCP
      name: taskd
    {{- if .Values.env.TASKD_ADMIN_ENABLED }}
    - port: {{ .Values.service.admin.port }}
      targetPort: 8080
      protocol: TCP
      name: admin
    {{- end }}
  selector:
    {{- include "taskd.selectorLabels" . | nindent 4 }}
