{{- if or .Values.ingress.taskd.enabled (and .Values.admin.enabled .Values.ingress.admin.enabled) -}}
{{- $fullName := include "taskd.fullname" . -}}
{{- if and .Values.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.ingress.annotations "kubernetes.io/ingress.class" .Values.ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "taskd.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- if .Values.ingress.taskd.enabled }}
    - host: {{ .Values.ingress.taskd.host | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.taskd.path }}
            {{- if and .Values.ingress.taskd.pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ .Values.ingress.taskd.pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ .Values.service.taskd.port }}
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ .Values.service.taskd.port }}
              {{- end }}
    {{- end }}
    {{- if and .Values.admin.enabled .Values.ingress.admin.enabled }}
    - host: {{ .Values.ingress.admin.host | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.admin.path }}
            {{- if and .Values.ingress.admin.pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ .Values.ingress.admin.pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ .Values.service.admin.port }}
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ .Values.service.admin.port }}
              {{- end }}
    {{- end }}
{{- end }}
