image:
  repository: x4121/taskd
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

admin:
  # If enabled, adds the taskd-admin sidecar to the pod.
  enabled: false

  image:
    repository: ghcr.io/my0n/taskd-admin
    pullPolicy: IfNotPresent
    tag: "v0.0.1"

# Persistence for taskd data
persistence:
  # If enabled, a Persistent Volume Claim will either be created or used.
  # If not enabled, the server just uses an emptyDir.
  enabled: false
  # Use an existing Persistent Volume Claim. If empty string (default), then a new one will be generated.
  existingClaim: ""
  # Access modes for the generated Persistent Volume Claim.
  accessModes:
    - ReadWriteOnce
  # Annotations for the generated Persistent Volume Claim.
  annotations: {}
  # The size of the generated Persistent Volume Claim. Defaults to 5Gi
  size: 5Gi
  # The storage class for the generated Persistent Volume Claim. If empty string (default), then the default provisioner will be used.
  storageClass: ""

env:
  CERT_CN: ""
  CERT_COUNTRY: ""
  CERT_LOCALITY: ""
  CERT_ORGANIZATION: ""
  CERT_STATE: ""
  extra: []
    #  - name: OTHER_ENV_VARIABLE
    #    value: some value

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  taskd:
    port: 53589
  admin:
    port: 8080

ingress:
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  taskd:
    enabled: false
    host: chart-example.local
    path: /
    pathType: ImplementationSpecific
  admin:
    enabled: false
    host: admin-example.local
    path: /
    pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
